# Generated by Django 4.1 on 2022-12-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentRegistrationdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Name",
                    models.CharField(
                        error_messages={"required": "Enter Your name please"},
                        max_length=30,
                    ),
                ),
                (
                    "Email",
                    models.EmailField(
                        error_messages={"required": "Enter Your email please"},
                        max_length=30,
                    ),
                ),
                (
                    "Password",
                    models.CharField(
                        error_messages={"required": "Enter Your password please"},
                        max_length=30,
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
